### ISSUE TITLE
The logo refreshes when I click the button "Create" if the form is not valid

### ISSUE THREAD

**Issue by smirik** [4xxi/caesarapp-old-server#17]
**Steps to reproduce:**
1. Go to caesarapp.
2. Do not enter anything.
3. Click "Create" button.

**Expected result:**
An error should occur.

**Actual result:**
1. No errors are shown.
2. The logo refreshes (see the screencast: http://scr.4xxi.com/es/screencast_2017-09-11_22-23-09.mp4).

**Comment by beshkenadze** [comment]
Moved to https://github.com/4xxi/caesarapp-web-client/issues/10
