### ISSUE TITLE
Fix the order of the expiration time

### ISSUE THREAD

**Issue by smirik** [4xxi/caesarapp-old-server#19]
For now, it looks like that there are the following option of the expiration dropdown:

1. 10 minutes.
2. 12 hours.
3. 24 hours.
4. 1 hour.

The options should be replaced with the following (**the order is important**):

1. 10 minutes.
2. 1 hour.
3. 12 hours.
4. 24 hours.
5.  7 days.
6. 30 days.

**Comment by beshkenadze** [comment]
Move to https://github.com/4xxi/caesarapp-web-client/issues/9
