### ISSUE TITLE
The logo is cut over sometimes

### ISSUE THREAD

**Issue by smirik** [4xxi/caesarapp-old-server#8]
**Steps to reproduce:**
1. Go to caesar-app website in the web.
2. Check the logo (see the screencast: http://scr.4xxi.com/ak/screencast_2017-09-11_18-46-51.mp4)

**Expected result:**
The logo should be visible.

**Actual result:**
It looks like that sometimes only a part of the logo is visible. Need to redo, logo should be always visible.

**Comment by beshkenadze** [comment]
Moved to https://github.com/4xxi/caesarapp-web-client/issues/11
